name: Build / Test
on: [push, pull_request]

jobs:
  generate:
    name: Generate parser
    runs-on: ubuntu-latest
    steps:
      - uses: tree-sitter/setup-action@v1
        with:
          install-lib: false
      - run: tree-sitter generate

      - name: Test
        run: tree-sitter test

      - name: Clone repo examples
        run: |
          echo rescript-lang/rescript-react \
          rescript-association/rescript-lang.org \
          tinymce/rescript-webapi \
          cca-io/rescript-material-ui \
          rescript-association/reanalyze \
          TheSpyder/rescript-nodejs.git \
          | xargs -n1 | xargs -I{} git clone --depth 1 https://github.com/{} examples/{}

      - name: Parse examples
        run: tree-sitter parse --quiet --stat examples/**/*.res*
