name: Build / Test
on: [push, pull_request]

jobs:
  generate:
    name: Generate parser
    runs-on: ubuntu-latest
    steps:
      - uses: tree-sitter/setup-action@v1
        with:
          install-lib: false
      - run: tree-sitter generate

      - name: Test
        run: tree-sitter test
